version: '3'
services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - .:/app
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - ./.env.local
    command: sh -c "npm run dev"
